---
title: "p8105_hw3_yx2711"
author: "Yingchen Xu"
date: "2022-10-15"
output: github_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(readxl)
library(ggridges)
library(patchwork)
library(p8105.datasets)

knitr::opts_chunk$set(
	echo = TRUE,
	warning = FALSE,
	fig.width = 8, 
  fig.height = 6,
  out.width = "90%"
)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```

#Problem 2

Read file and clean names.
Use `mutate()` to add a type variable to indicate that whether the day is a weekend or a weekday.
Use `Pivot_longer()` to transform the dataset from the wide format to a long format and name the columns as "activity_id" and "counts"
```{r}
activity = read.csv("data/accel_data.csv") %>% 
  janitor::clean_names() %>% 
  mutate(
    type = ifelse(day == c("Saturday", "Sunday"), "weekend", "weekday")
  ) %>% 
  pivot_longer(
    activity_1:activity_1440,
    names_to = "minute",
    names_prefix = "activity_",
    values_to = "counts"
  )
```

